
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.146.128:3306/fixcomputer
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.146.128
      port: 6379
      password: 123




mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 8080
logging:
  level:
    com.baomidou.mybatisplus.core.mapper: DEBUG

minio:
  url: http://192.168.146.128:9000
  accessKey: minio
  secretKey: minio123

alipay:

  apiId: 

  appPrivateKey: 

  alipayPublicKey: 
  notifyUrl:

